spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/ecommerce?characterEncoding=utf8&serverTimezone=UTC
    username: ecommerce
    password: springstudy
    pool:
      max-size: 50
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5433/ecommerce?characterEncoding=utf8&serverTimezone=UTC
    user: ecommerce
    password: springstudy

